%%% Anıl ARSLAN 2303980
clc; clear; % close all;
addpath(genpath([pwd '/library']));

d = 1e3;
posMonostatic = [0; 0; 0];
% posMultistatic = [posMonostatic, [0 -2*d 2*d; 0 d d; 0 0 0]];
% posMultistatic = [[-2*d -d; 0 0; 0 0], posMonostatic, [d 2*d; 0 0; 0 0]];
posMultistatic = [[-d -0.7*d; sqrt(3)*d 0.7*d; 0 0], posMonostatic, [0.7*d d; 0.7*d sqrt(3)*d; 0 0]];

arrayRX = planarArray( ...
    "numberOfElements", [11 1], ...
    "numberOfElements", [1 1], ...
    "rpm", 0);
arrayTX = planarArray( ...
    "numberOfElements", [5 1], ...
    "numberOfElements", [1 1], ...
    "rpm", 0);

receivers = receivingNode( ...
    'position', posMultistatic, ...
    'position', posMultistatic, ...
    'array', arrayRX, ...
    'samplingFrequency', 2e6, ... 5e6, ... 2e7
    'CPIsecond', 10e-6); % 15e-6
% receivers.settingsreceiver("beamformingMode", "bypass");
% receivers.setbeamcenters("beamCentersAzimuth", -5 : 5 : 5);

transmitters = transmittingNode( ...
    'position', posMultistatic, ...
    'array', arrayTX, ...
    'inputPower_W', 1e3, ...
    'carrierFrequency', 1e9, ...
    'pulseWidth', 5e-7); % 1e-6
transmitters.setLFM( ...
    "bandWidth", 1e6, ... 5e6
    "frequencyDirection", "decreasing");

transmitterArrays = [transmitters.array];
receiverArrays = [receivers.array];

% transmitterArrays.setorientation( ...
%     "yaw", [45 135 90 0 180], ...
%     "scanDirection", ["ccw" "cw" "cw" "cw" "cw"]);
% receiverArrays.setorientation( ...
%     "yaw", [45 135 90 0 180], ...
%     "scanDirection", ["ccw" "cw" "cw" "cw" "cw"]);

transmitterArrays.setorientation("yaw", 90);
receiverArrays.setorientation("yaw", 90);
receiverArrays.setorientation( ...
    "yaw", [30 45 90 135 150]);

network = radarNetwork( ...
    'receivingNodes', receivers, ...
    'transmittingNodes', transmitters);
network.settingsnetwork( ...
    "networkMode", "multiStatic", ...
    'fractionalDelayMode', 'off', ...
    'fractionalDelayMode', 'sinc-based', ...
    "beamTime", 1e-2);
network.activitycontrol( ...
    "transmittingNodeActivity", [0 0 1 0 0], ...
    "receivingNodeActivity", [1 1 1 1 1]);
network.setsurveillance("staticBeam");
network.setsynchronization( ...
    "timeOffsetBistaticPairs", 0, ...
    "timeDeviationBistaticPairs", 5e-8, ... Ts/10
    "timeDeviationBistaticPairs", 5e-7, ... Ts
    "frequencyOffsetBistaticPairs", 0, ...
    "frequencyDeviationBistaticPairs", 0 ... 5e8
    );
% network.visualizenetwork; view(0, 90);

targets = target( ...
    ...'position', [-d/2 0 d/2 -d; d/2 d 3*d/2 d; 0 0 0 0].*(.9 + 0.2*rand(3, 4)), ...
    ...'position', [-d/2 0 d/2; d/2 d 3*d/2; 0 0 0], ...
    ...'position', [-d/2 -d d/2; d/2 d 3*d/2; 0 0 0], ...
    'position', [-d/2 d/2; d/2 3*d/2; 0 0], ...
    ...'position', [d/2; 3*d/2; 0], ...
    ...'position', [d/2; d/2; 0], ...
    ...'position', [-3*0.0484434*d; 0.0515566*d; 0], ...
    ...'position', [-0.0484434*d; 30*0.0515566*d; 0], ...
    ...'position', [-3*0.0484434*d; 10*0.0515566*d; 0], ...
    'meanRCS_dbsm', 0, ...
    'velocity', [0; -0*d/2; 0]);
int = interface( ...
    'network', network, ...
    'targets', targets);
int.configure( ...
    'noise', 1, ...
    'directPath', 0, ...
    "pathLoss", 1, ...
    "timeSynchronization", 1, ...
    "frequencySynchronization", 1, ...
    'spatialCoherency', 'incoherent', ...
    'swerling', 1);

sp = spu( ...
    "interfaces", int, ...
    "gridResolution", [100 100 6000]);
sp.setintegrationindices;
sp.configure( ...
    "PFA", 1e-6, ...
    "processingAlgorithm", 6, ...
    "detectionAlgorithm", "thresholding", ...
    "detectionAlgorithm", "peak", ...
    "detectionAlgorithm", "OMPjoint", ... 
    "numberOfTargets", nan, ...
    "neighbourOffset", 1, ...
    "seed", 0, ...
    "seedShuffle", 0, ...
    "numberOfTrials", 100, ...
    'numberOfTrialsParallel', 1, ...
    'numberOfTrialsParallel', 100);

%%
% arrayRX.visualizearray;
% arrayTX.visualizearray;
% network.visualizenetwork;
% int.visualizescenario("showPattern", 1);
% int.visualizereceivedsignals;
% int.visualizebeamformedsignals;
% sp.visualizefilteredsignals("trialID", 1);

trialID = 38;
figID = 50;
sp.configure( ...
    "seed", 0, ...
    "neighbourOffset", 1);
sp.applycompression( ...
    "saveResiduals", 1);
sp.visualizeintegratedsignals( ...
    "figureID", figID + 2, ...
    "iterationID", 1 : 10, ...
    "trialID", trialID, ...
    "plotMode", "image");
sp.visualizecompression( ...
    "figureID", figID + 100, ...
    "trialID", trialID);
%%
% sp.setmatchfilteredsignals;
% sp.visualizeintegratedsignals( ...
%     "figureID", 5140, ...,
%     "trialID", 1);
% sp.visualizeestimation;
%%
clc;
% [PD, PFA] = sp.simulatedetection;
sp.configure( ...
    "seed", 0, ...
    "neighbourOffset", 100, ...
    "numberOfTrials", 1, ...
    "numberOfTrialsParallel", 1000);
sp.simulatecoverage( ...
    "meanRCS_dbsm", 10, ...
    "onCellCenters", 1);
close all;
sp.visualizecoveragesimulation( ...
    "contourLevelDetection", 0.85, ...
    "saveDirectory", "figures/multiStatic/centerOfCell/senkron", ...
    "saveDirectory", "figures/multiStatic/centerOfCell/asenkron", ...
    "saveDirectory", "figures/multiStatic/randomInCell/senkronFarkliKonfigurasyon", ...
    ..."saveDirectory", "figures/multiStatic/randomInCell/asenkron", ...
    "saveFigures", 1 ...
    );
%%
% sp.visualizereceiveroperatingcharacteristics;
% sp.visualizedetectioncharacteristics("PFA", 1e-4);
%%
% tic;
% detection = sp.startsimulation("duration", 0.5);
% toc
%%
% sp.configure("processingAlgorithm", 2);
% sp.visualizedetectioncharacteristics("PFA", 1e-6);
% sp.configure("processingAlgorithm", 6);
% sp.visualizedetectioncharacteristics("PFA", 1e-6);