%%% Anıl ARSLAN 2303980
clc; clear; % close all;
addpath(genpath([pwd '/library']));

d = 1e3;
posMonostatic = [0; 0; 0];
posMultiMonostatic = [posMonostatic, [d; 0; 0]];

arrayRX = planarArray( ...
    "numberOfElements", [5 1], ...
    "rpm", 0);
arrayTX = planarArray( ...
    "numberOfElements", [1 1], ...
    "rpm", 0);

receivers = receivingNode( ...
    'position', posMultiMonostatic, ...
    'array', arrayRX, ...
    'samplingFrequency', 2e6, ... 5e6, ... 2e7
    'CPIsecond', 10e-6); % 15e-6
receivers.settingsreceiver("beamformingMode", "bypass");
% receivers.setbeamcenters("beamCentersAzimuth", -5 : 5 : 5);

transmitters = transmittingNode( ...
    'position', posMultiMonostatic, ...
    'array', arrayTX, ...
    'inputPower_W', 1e3, ...
    'carrierFrequency', 1e9, ...
    'pulseWidth', 5e-7); % 1e-6
transmitters.setLFM( ...
    "bandWidth", 1e6, ... 5e6
    "frequencyDirection", "decreasing");

transmitterArrays = [transmitters.array];
receiverArrays = [receivers.array];

transmitterArrays.setorientation("yaw", 90);
receiverArrays.setorientation("yaw", 90);
% transmitterArrays.steer("steeringAzimuth", 30);

network = radarNetwork( ...
    'receivingNodes', receivers, ...
    'transmittingNodes', transmitters);
network.settingsnetwork( ...
    "networkMode", "monoStatic", ...
    "beamTime", 1e-2);
network.activitycontrol( ...
    "transmittingNodeActivity", [1 0], ...
    "receivingNodeActivity", [1 0]);
network.setsurveillance("staticBeam");
network.setsynchronization( ...
    "timeOffsetBistaticPairs", 0, ...
    "timeDeviationBistaticPairs", 0, ... 1e-6
    "frequencyOffsetBistaticPairs", 0, ...
    "frequencyDeviationBistaticPairs", 0 ... 5e8
    );

targets = target( ...
    'position', [d/2; d/2; 0], ...
    'position', [-2.5*0.0484434*d; 0.0515566*d; 0], ...
    'position', [-3*0.0484434*d; 10*0.0515566*d; 0], ...
    'meanRCS_dbms', 0, ...
    'velocity', [0; -0*d/2; 0]);
int = interface( ...
    'network', network, ...
    'targets', targets);
int.configure( ...
    'noise', 1, ...
    'directPath', 0, ...
    "pathLoss", 1, ...
    "timeSynchronization", 1, ...
    "frequencySynchronization", 1, ...
    'spatialCoherency', 'coherent', ...
    'swerling', 1);

sp = spu("interfaces", int, "gridResolution", [100 100 6000]);
sp.setintegrationindices;
sp.configuremonostatic( ...
    'CFAR', 1, ...
    'groupingCloseness', 3, ...
    'numberOfGuardCells', 1, ...
    'numberOfTrainingCells', 20, ...
    'interpolationMF', 0, ...
    'interpolationDF', 1, ...
    'removeBoundaryDetectionDF', 1, ...
    'removeBoundaryDetectionMF', 1);
sp.configure( ...
    "PFA", 1e-6, ...
    "processingAlgorithm", 2, ...
    "detectionAlgorithm", "thresholding", ...
    "detectionAlgorithm", "peak", ...
    "detectionAlgorithm", "OMP", ... 
    "numberOfTargets", nan, ...
    "neighbourOffset", 1, ...
    "seed", 0, ...
    "seedShuffle", 0, ...
    "numberOfTrials", 1, ...
    'numberOfTrialsParallel', 1, ...
    'numberOfTrialsParallel', 100);

%%
% arrayRX.visualizearray;
% network.visualizenetwork;
% int.visualizescenario("showPattern", 1);
% int.visualizereceivedsignals;
% int.visualizebeamformedsignals;
% sp.visualizefilteredsignals("trialID", 1);
%
figID = 50;
sp.configure( ...
    "seed", 0, ...
    "neighbourOffset", 1);
sp.setmatchfilteredsignals;
sp.applycompression( ...
    "saveResiduals", 1);
sp.visualizeintegratedsignals( ...
    "figureID", figID + 2, ...,
    "iterationID", 1 : 2, ...
    "trialID", 3, ...
    "monoStaticNetworkRXID", 1, ...
    "monoStaticNetworkCHID", 1, ...
    "plotMode", "image");
sp.visualizecompression( ...
    "figureID", figID + 100, ...
    "trialID", 1, ...
    "monoStaticNetworkRXID", 1, ...
    "monoStaticNetworkCHID", 1);
%%
sp.visualizeintegratedsignals( ...
    "trialID", 3, ...
    "monoStaticNetworkRXID", 1, ...
    "monoStaticNetworkCHID", 1);
% sp.visualizeestimation;
%%
clc
% [PD, PFA] = sp.simulatedetection;
sp.configure( ...
    "seed", 0, ...
    "neighbourOffset", 100, ...
    "numberOfTrials", 1, ...
    "numberOfTrialsParallel", 100);
sp.simulatecoverage( ...
    "meanRCS_dbms", 0, ...
    "onCellCenters", 1);
sp.visualizecoveragesimulation( ...
    "saveFigures", 1, ...
    "saveDirectory", "figures/monoStaticCenterOFCell/neighbour100" ...
    );
%%
% sp.visualizereceiveroperatingcharacteristics;
% sp.visualizedetectioncharacteristics("PFA", 1e-4);
%%
% tic;
% detection = sp.startsimulation("duration", 0.5);
% toc
%%
% int.configure("swerling", 0);
% sp.visualizereceiveroperatingcharacteristics;
% sp.visualizedetectioncharacteristics("PFA", 1e-6);
% int.configure("swerling", 1);
% sp.visualizereceiveroperatingcharacteristics;
% sp.visualizedetectioncharacteristics("PFA", 1e-6);