%%% Anıl ARSLAN 2303980
clc; clear; close all;
addpath(genpath([pwd '/library']));

d = 1e3;
posRX = [d -d; 0 0; 0 0];
posTX = [0; -d; 0];

arrayRX = planarArray( ...
    "numberOfElements", [11 11]);
arrayTX = planarArray( ...
    "numberOfElements", [5 5]);
arrayRX.steer("steeringAzimuth", 30);

receivers = receivingNode( ...
    'position', posRX, ...
    'array', arrayRX, ...
    'samplingFrequency', 2e6, ...
    'CPIsecond', 10e-6);

transmitters = transmittingNode( ...
    'position', posTX, ...
    'array', arrayTX, ...
    'inputPower_W', 1e3, ...
    'carrierFrequency', 1e9, ...
    'pulseWidth', 5e-7);
transmitters.setLFM( ...
    "bandWidth", 1e6, ...
    "frequencyDirection", "decreasing");

network = radarNetwork( ...
    'receivingNodes', receivers, ...
    'transmittingNodes', transmitters);
network.settingsnetwork( ...
    "networkMode", "multiStatic", ...
    "beamTime", 1e-2);

targets = target( ...
    ... 'position', [1.03770999999961; 1.03770999999961; 0], ...
    'position', [ ...
    1.03770999999961 0; ...
    -1389.6 0; ...
    0 0], ...
    'meanRCS_dbsm', 0);

int = interface( ...
    'network', network, ...
    'targets', targets);
int.configure( ...
    'noise', 1, ...
    'directPath', 0, ...
    'spatialCoherency', 'coherent', ...
    'swerling', 1 );

sp = spu( ...
    "interface", int, ...
    "gridResolution", [100 100 6000]);
sp.setintegrationindices;
sp.configure( ...
    "PFA", 1e-6, ...
    "processingAlgorithm", 6, ...
    "seed", 0, ...
    "seedShuffle", 1, ...
    "numberOfTrials", 200, ...
    'numberOfTrialsParallel', 200);

% arrayRX.visualizearray;
% arrayTX.visualizearray;
% network.visualizenetwork;
int.visualizescenario("showPattern", 1);
%%
int.visualizereceivedsignals;
sp.visualizefilteredsignals;
%%
% sp.setmatchfilteredsignals;
sp.visualizeintegratedsignals("trialID", 31); % 17 20
% sp.visualizeestimation;
%%
% [PD, PFA] = sp.simulatedetection;
%%
sp.visualizereceiveroperatingcharacteristics;
sp.visualizedetectioncharacteristics("PFA", 1e-4);