%%% Anıl ARSLAN 2303980
clc; %clear; close all;
d = 1e3;
scanD = linspace(-1.5*d, 1.5*d, 100);
receivers = receivingNode( ...
    'position', [d 0 -d; 0 d -d; 0 0 0], ...
    'samplingFrequency', 4e7);
transmitters = transmittingNode( ...
    'position', [-d 0; 0 -d; 0 0], ...
    'inputPower', 1e3, ...
    'carrierFrequency', 1e9, ...
    'pulseWidth', 1e-6);
network = radarNetwork( ...
    'receivingNodes', receivers, ...
    'transmittingNodes', transmitters);
targets = target( ...
    'y', scanD, ...
    'x', scanD, ...
    'velocity', [50; 50; 50]);
int = interface( ...
    'network', network, ...
    'targets', targets);
%%
int.visualizeisocurves( ...
    'curves', "all", ...
    'receivingNodeID', 3, ...
    'transmittingNodeID', 2);