%%% Anıl ARSLAN 2303980
clc; clear; close all;
addpath(genpath([pwd '/library']));

arrayRX = uniformPlanarArray("numberOfElements", [32 1]);
arrayTX = uniformPlanarArray("numberOfElements", [32 1]);
d = 1e3;
receivers = receivingNode( ...
    'position', [d; 0; 0], ...
    'array', arrayRX, ...
    'samplingFrequency', 2e7, ...
    'CPIsecond', 10e-6);
transmitters = transmittingNode( ...
    'position', [0; -d; 0], ...
    'array', arrayTX, ...
    'peakPower_W', 1e3, ...
    'carrierFrequency', 1e9, ...
    'pulseWidth', 1e-6);
transmitters.setLFM( ...
    "bandWidth", 5e6, ...
    "frequencyDirection", "decreasing");
network = radarNetwork( ...
    'receivingNodes', receivers, ...
    'transmittingNodes', transmitters);
numberOfPoints = 10000;
phi = linspace(-180, 180, numberOfPoints);
targets = target( ...
    'position', [ ...
    2*d*cosd(phi); ...
    2*d*sind(phi); ...
    zeros(1, numberOfPoints)], ...
    'meanRCS_dbms', -25);
int = interface( ...
    'network', network, ...
    'targets', targets);
% arrayRX.visualizearray;
% arrayTX.visualizearray;
% network.visualizenetwork;

arrayTX.setorientation("yaw", 90);
arrayRX.setorientation("yaw", 90);
int.visualizescenario("showPattern", true);