% Anıl Arslan 2303980
%% Binary combining
clc; clear; close all;
set(groot, "defaultFigurePosition", [680 458 560 420]);
detector = detector( ...
    "globalPFA", 1e-6, ...
    "numberOfSensors", [1 2 3 5 7 9 11], ...
    "SNR_input_dB", 8, ...
    "localPFA", logspace(0, -6, 31) ...
    );
detector.setalgorithm( ...
    "binaryDetectionRule", "notSpecified", ...
    "binaryDetectionConstraint", "fixedGlobal|LocalPFA", ...
    "signalAmplitudeModel", "decorrelatedExponential", ...
    "signalPhaseModel", "decorrelatedUniform", ...
    "globalFusionRule", "BC" ...
    );
fig = detector.visualize( ...
    "x_axis", "localPFA", ...
    "y_axis", "globalPD", "dataType", "analytical");
% 
figureName = 'binary_combining';
savefig(fig, ['C:\GitRepo\MSRS\figureGenerator\figures\' figureName '.fig']);
saveas(fig, ['C:\GitRepo\MSRS\figureGenerator\figures\' figureName '.eps'], 'epsc');

%% Square Law Combining
clc; clear; close all;
set(groot, "defaultFigurePosition", [680 458 560 420]);
detector = detector( ...
    "globalPFA", 1e-6, ...
    "numberOfSensors", [1 2 3 5 7 9 11], ...
    "SNR_input_dB", 8, ...
    "localPFA", logspace(0, -6, 31) ...
    );
detector.setalgorithm( ...
    "signalAmplitudeModel", "decorrelatedExponential", ...
    "signalPhaseModel", "decorrelatedUniform", ...
    "globalFusionRule", "SLC" ...
    );
fig = detector.visualize( ...
    "x_axis", "localPFA", ...
    "y_axis", "globalPD", "dataType", "analytical");

figureName = 'square_law_combining';
savefig(fig, ['C:\GitRepo\MSRS\figureGenerator\figures\' figureName '.fig']);
saveas(fig, ['C:\GitRepo\MSRS\figureGenerator\figures\' figureName '.eps'], 'epsc');

%% Equal SNR
clc; clear; close all;
set(groot, "defaultFigurePosition", [680 458 560 420]);

pfaLocal = logspace(0, -6, 31);
algorithms = ["BC", "SLC"];

fig = figure;
for algorithm = algorithms
    detector = detector( ...
        "globalPFA", 1e-6, ...
        "numberOfSensors", 7, ...
        "SNR_input_dB", 8, ...
        "localPFA", pfaLocal ...
        );
    detector.setalgorithm( ...
        "binaryDetectionRule", "notSpecified", ...
        "binaryDetectionConstraint", "fixedGlobal|LocalPFA", ...
        "signalAmplitudeModel", "decorrelatedExponential", ...
        "signalPhaseModel", "decorrelatedUniform", ...
        "globalFusionRule", algorithm ...
        );
    pd = squeeze(detector.globalPD);
    semilogx(pfaLocal, pd, 'LineWidth', 2); hold on;
end
grid on; grid minor;
ylim([0, 1]);
xlabel('Local Probability of False Alarm');
ylabel('Global Probability of Detection');
algorithms(algorithms == "WSLCbiased") = "WSLC";
legend(algorithms, 'Location', 'best');

figureName = 'equal_snr';
savefig(fig, ['C:\GitRepo\MSRS\figureGenerator\figures\' figureName '.fig']);
saveas(fig, ['C:\GitRepo\MSRS\figureGenerator\figures\' figureName '.eps'], 'epsc');

%% Different SNR
clc; clear; close all;
set(groot, "defaultFigurePosition", [680 458 560 420]);

pfaLocal = logspace(0, -6, 31);
algorithms = ["BC", "SLC", "WSLCbiased"];

fig = figure;
for algorithm = algorithms
    detector = detector( ...
        "globalPFA", 1e-6, ...
        "numberOfSensors", 7, ...
        "SNR_input_dB", 8, ...
        "localPFA", pfaLocal ...
        );
    detector.setalgorithm( ...
        "binaryDetectionRule", "notSpecified", ...
        "binaryDetectionConstraint", "fixedGlobal|LocalPFA", ...
        "signalAmplitudeModel", "decorrelatedExponential", ...
        "signalPhaseModel", "decorrelatedUniform", ...
        "globalFusionRule", algorithm ...
        );
    rng(1975); detector.randomSNRwithFixedAverage("rangeSNR_dB", 20);
    snr = detector.SNR_input_dB{1};
    pd = squeeze(detector.globalPD);
    semilogx(pfaLocal, pd, 'LineWidth', 2); hold on;
end
grid on; grid minor;
ylim([0, 1]);
xlabel('Local Probability of False Alarm');
ylabel('Global Probability of Detection');
algorithms(algorithms == "WSLCbiased") = "WSLC";
legend(algorithms, 'Location', 'best');

figureName = 'different_snr';
savefig(fig, ['C:\GitRepo\MSRS\figureGenerator\figures\' figureName '.fig']);
saveas(fig, ['C:\GitRepo\MSRS\figureGenerator\figures\' figureName '.eps'], 'epsc');